services:
  app:
    build: .
    image: crecerlabs-voiceapp-server
    container_name: crecerlabs-voiceapp-server
    # command: uvicorn app.main:main --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 8000:8000
      - 5678:5678 # OPEN FOR DEBUGGING.  REMOVE FOR PRODUCTION
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development