services:
  app:
    build: .
    image: crecerlabs-voiceapp-image
    container_name: crecerlabs-voiceapp-container
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80     # UI
      - 5000:5000 # Websocket API
      - 5678:5678 # Debugging. ** REMOVE FOR PRODUCTION **
    volumes:
      - .:/code
    devices:
      - "/dev/snd:/dev/snd" # Linux host mappping
    environment:
      - PYHTONNUNBUFFERED=1
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    stdin_open: true # This is required for some interactive applications
    tty: true
    #Add necessary capablities and privileges
    cap_add:
      - SYS_ADMIN
    privileged: true